matrix:

  include:
    - language: go
      go: 1.12.x
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:masterminds/glide'
          packages:
            - g++-6
            - gcc-6
            - glide
      cache:
        apt: true
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

      before_cache:
        #- rm -rf $GOPATH/src/github.com/coinexchain/dex/*

      after_success:
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-pro -repotoken $COVERALLS_TOKEN

      before_install:
        - export GO111MODULE=on
        - export GOROOT=$(go env GOROOT)
        - export CXX="g++-6" CC="gcc-6"
        - export PATH=$PATH:$HOME/gopath/bin

      install:
        - cd -
        - go mod tidy
        - go mod vendor
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls

      script:
        - ./scripts/check.sh

    - &ft_job
      language: go
      python: 3.7
      go: 1.12.x
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            #- sourceline: 'ppa:longsleep/golang-backports'
          packages:
            #- golang-1.12
            - python3-pip
            - parallel
            - g++-6
            - gcc-6
            - bzr
            - build-essential

      cache:
        apt: true
        directories:
          - $CACHE_DIR
          - $HOME/.cache/pip
          - $HOME/gopath/pkg/mod
      before_install:
        - export GO111MODULE=on
        - export GOROOT=$(go env GOROOT)
        - export CXX="g++-6" CC="gcc-6"
        - export PATH=$PATH:$HOME/gopath/bin
      install:
        - cd -
        - go env
        #- pip3 install --upgrade pip
        - python3 --version
        - pip3 --version
        - go get github.com/rakyll/statik
        - go mod tidy
        - go mod vendor
        - make statik-swagger
        - make build-linux
      services:
        - docker

      before_script:
#        - chmod +x ./scripts/functional_test.sh

      after_success:
        - rm ~/.docker/config.json

      env:
        global:
          - CACHE_DIR=$HOME/.cache/docker
      script:
        - docker build . --tag=coinexchain/cetdtest
        - scripts/functional_test.sh 4 0

    - <<: *ft_job
      script:
        - docker build . --tag=coinexchain/cetdtest
        - scripts/functional_test.sh 4 1

    - <<: *ft_job
      script:
        - docker build . --tag=coinexchain/cetdtest
        - scripts/functional_test.sh 4 2

    - <<: *ft_job
      script:
        - docker build . --tag=coinexchain/cetdtest
        - scripts/functional_test.sh 4 3

notifications:
  email:
    on_success: change
    on_failure: always